#
# Run pre-commit hooks. You can run them without installing
#  the hook with
#
# $ pre-commit run --all-files
#
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_stages:
  - pre-commit
exclude: "^archived/"
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  # Manage spaces.
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-added-large-files
  - id: check-symlinks
  - id: mixed-line-ending
    args: [--fix=lf]
  # Check file syntax/format
  - id: check-xml
  - id: check-json
  - id: check-yaml
    args: [--allow-multiple-documents]
    exclude: 'ex-.*\.yaml'
  # Security checks.
  - id: detect-private-key
  - id: detect-aws-credentials
    args:
    # See https://github.com/pre-commit/pre-commit-hooks/issues/174
    - --allow-missing-credentials
- repo: https://github.com/google/yamlfmt
  rev: v0.21.0
  hooks:
  - id: yamlfmt
    files: \.(yaml|yml)$
    exclude: 'config\.yaml|ex-.*\.yaml'
#
# Python linters.
#
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.14.13
  hooks:
  # Run the linter.
  - id: ruff
    args: [--fix]
    files: ^python-high-school/
    exclude: ^python-for-sysadmin|\.ipynb$
  - # Run the formatter.
    id: ruff-format
    files: ^python-high-school/
    exclude: ^python-for-sysadmin|\.ipynb$
#
# Security linters.
#
- repo: https://github.com/bridgecrewio/checkov.git
  rev: 3.2.507  # change to tag or sha
  hooks:
  - id: checkov
  - id: checkov_secrets
    stages: ["pre-push"]
- repo: local
  hooks:
  - id: trufflehog
    name: TruffleHog v3.93.3
    description: Detect secrets in your data.
    entry: bash -c 'docker run -c 2 --rm -v "$(pwd):/workdir" -i --rm
      docker.io/trufflesecurity/trufflehog@sha256:06c1f230512cbb694954716fa5e0adbfb95809c7bfb5a50c25110847417b69db git file:///workdir --since-commit
      HEAD --results=verified,unknown --fail'
    language: system
    stages: ["pre-push"]
- repo: https://github.com/zizmorcore/zizmor-pre-commit
  rev: v1.22.0
  hooks:
    - id: zizmor
