- hosts: web
  tasks:
  - name: Create a new keypair on localhost
    delegate_to: 
    run_once: yes
    user:
      name: root
      generate_ssh_key: yes
      ssh_key_file: /root/id_ecdsa_new

  - name: Create a new user with associated ssh keys
    user:
      name: fizz
      ...
      ...

  - name: >
      Install remotely a local PK. Use the
      authorized_key docs to complete this task
    authorized_key:
      user: 
      state: 

  - name: Add this host to the inventory
    add_host: 
      ansible_ssh_host: 
      hostname: "{{ansible_default_ipv4.address}}"
      groups: test

#
# This tasklist will connect to test
#  hostgroup via ssh instead eg. docker
#  (see ansible.cfg). The following
#  vars will override the default connection
#  parameters.
#

- hosts: test
  tags: test
  vars:
    ansible_connection: ssh
    ansible_user: fizz
    host_key_checking: no
    ansible_private_key_file: /root/id_ecdsa_new
  tasks:
  - name: A test command
    shell: hostname
    
  
