- hosts: localhost
  tasks:
  - name: Iterate thru environment
    debug:
      var: >
        ansible_env.{{item}}
    with_items: >
        {{ansible_env | map('regex_search', '^PATH') | select('string') | list  }}
