- hosts: innodb
  tasks:
  - package:
      name: https://dev.mysql.com/get/mysql57-community-release-el7-11.noarch.rpm

  - package:
      name: "{{item}}"
    with_items:
    - mysql-community-server
    - mysql-community-client
    - mysql-utilities
    - mysql-router
    - mysql-shell

  - name: Install sshd
    package:
      name: openssh

  - name: Start
    service:
      name: sshd
      state: started
      enabled: yes

  - name: Distribute keys
    copy:
      src: "{{item}}"
      dest: /root/.ssh/
      mode: 0600
    with_items:
    - id_ecdsa_inno
    - authorized_keys

  - name: Configure innodb cluster
    include: initialize-innodbcluster.yml
