[tox]
envlist = py3
skipsdist = True

[testenv]
deps =
  -r requirements.txt
  -r requirements-api.txt
allowlist_externals =
  bash
commands =
  bash -c 'cd notebooks && jupyter notebook . '

[testenv:api]
deps =
  connexion[swagger-ui]
  starlette
  httpx
  pytest
  anyio[trio]
  http-sf
commands =
  pytest {posargs:notebooks/oas3/test_throttling_quota.py} -v

[testenv:make]
# XXX: Update notedown so we don't need setuptools.
deps =
  setuptools
  git+https://github.com/ioggstream/notedown
  jupyter
  nbconvert
passenv =
  SHOW_SOLUTIONS
allowlist_externals =
  make
commands =
  make
