services:
  course:
    build: .
    volumes:
    - ".:/code:rw"
    working_dir: /code/notebooks
    user: "1000"
    environment:
    - "HOME=/code/notebooks"
    ports:
    - "8888:8888"
    command:
    - notebook
    - --ip=0.0.0.0
