
# Load variables from the following files
- hosts: course
  vars_files:
  - vaultfile.yml
  tasks:
  - name: Ensure /root/.ssh is present
    file: path=/root/.ssh owner=root group=root state=directory
  - name: Copy there my key
    copy: src=id_ansible.pub dest=/root/.ssh/authorized_keys mode=0600 owner=root group=root
    
    